// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ProcessingData")>]
[<assembly: AssemblyProductAttribute("ProcessingData")>]
[<assembly: AssemblyDescriptionAttribute("Processing Data with F#")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ProcessingData"
    let [<Literal>] AssemblyProduct = "ProcessingData"
    let [<Literal>] AssemblyDescription = "Processing Data with F#"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
